name: Keep Alive
on:
  schedule:
    - cron: '* * * * *' # Every 14 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping server
        run: curl -X GET  https://sd-fashion.onrender.com/api/keep-alive